package com.electrovotesuperx.dao.AdminDAO;

import com.electrovotesuperx.config.firebaseConfig.FirebaseConfig;
import com.electrovotesuperx.exception.FirestoreException;
import com.electrovotesuperx.model.AdminModel.ElectionData;
import com.google.gson.*;

import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/**
 * ElectionDAO handles all Firestore REST API calls for elections.
 *
 * Firestore collection: Elections
 * Document ID: election.getId() (UUID generated by caller)
 *
 * Firestore REST base:
 *   https://firestore.googleapis.com/v1/projects/electravote-ca872/databases/(default)/documents/Elections/
 */
public class ElectionDAO {

    private static final HttpClient CLIENT = HttpClient.newHttpClient();
    private static final String BASE_URL =
            "https://firestore.googleapis.com/v1/projects/" + FirebaseConfig.PROJECT_ID + "/databases/(default)/documents/Elections";
    private static final Gson GSON = new Gson();

    // =========================================================
    // CREATE / UPDATE ELECTION  (PATCH = upsert)
    // =========================================================

    public static boolean saveElection(ElectionData election, String idToken)
            throws FirestoreException {

        String url = BASE_URL + "/" + encode(election.getId())
                + "?updateMask.fieldPaths=title"
                + "&updateMask.fieldPaths=description"
                + "&updateMask.fieldPaths=startDateTime"
                + "&updateMask.fieldPaths=endDateTime"
                + "&updateMask.fieldPaths=status"
                + "&updateMask.fieldPaths=positions"
                + "&updateMask.fieldPaths=joinCode"
                + "&updateMask.fieldPaths=createdAt";

        JsonObject fields = new JsonObject();
        fields.add("title", str(election.getTitle()));
        fields.add("description", str(election.getDescription()));
        fields.add("startDateTime", str(election.getStartDateTime()));
        fields.add("endDateTime", str(election.getEndDateTime()));
        fields.add("status", str(election.getStatus()));
        fields.add("positions", toArrayValue(election.getPositions()));
        fields.add("joinCode", str(election.getJoinCode()));
        fields.add("createdAt", intVal(election.getCreatedAt()));

        JsonObject body = new JsonObject();
        body.add("fields", fields);

        HttpRequest req = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Authorization", "Bearer " + idToken)
                .header("Content-Type", "application/json")
                .method("PATCH", HttpRequest.BodyPublishers.ofString(body.toString(), StandardCharsets.UTF_8))
                .build();

        HttpResponse<String> res;
        try {
            res = CLIENT.send(req, HttpResponse.BodyHandlers.ofString());
        } catch (IOException | InterruptedException e) {
            throw new FirestoreException("Unable to save election data.", e);
        }
        System.out.println("[ElectionDAO.saveElection] " + res.statusCode() + " " + res.body());
        return res.statusCode() >= 200 && res.statusCode() < 300;
    }

    // =========================================================
    // UPDATE POSITIONS ONLY
    // =========================================================

    public static boolean updatePositions(String electionId, List<String> positions, String idToken)
            throws FirestoreException {

        String url = BASE_URL + "/" + encode(electionId)
                + "?updateMask.fieldPaths=positions";

        JsonObject fields = new JsonObject();
        fields.add("positions", toArrayValue(positions));

        JsonObject body = new JsonObject();
        body.add("fields", fields);

        HttpRequest req = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Authorization", "Bearer " + idToken)
                .header("Content-Type", "application/json")
                .method("PATCH", HttpRequest.BodyPublishers.ofString(body.toString(), StandardCharsets.UTF_8))
                .build();

        HttpResponse<String> res;
        try {
            res = CLIENT.send(req, HttpResponse.BodyHandlers.ofString());
        } catch (IOException | InterruptedException e) {
            throw new FirestoreException("Unable to update election positions.", e);
        }
        return res.statusCode() >= 200 && res.statusCode() < 300;
    }

    // =========================================================
    // DELETE ELECTION
    // =========================================================

    public static boolean deleteElection(String electionId, String idToken)
            throws FirestoreException {

        String url = BASE_URL + "/" + encode(electionId);

        HttpRequest req = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Authorization", "Bearer " + idToken)
                .DELETE()
                .build();

        HttpResponse<String> res;
        try {
            res = CLIENT.send(req, HttpResponse.BodyHandlers.ofString());
        } catch (IOException | InterruptedException e) {
            throw new FirestoreException("Unable to delete election.", e);
        }
        return res.statusCode() >= 200 && res.statusCode() < 300;
    }

    // =========================================================
    // GET ALL ELECTIONS FOR AN ORG (query by joinCode)
    // =========================================================

    public static List<ElectionData> getElectionsByOrg(String joinCode, String idToken)
            throws FirestoreException {

        List<ElectionData> result = new ArrayList<>();
        String url = BASE_URL + "?pageSize=300";

        HttpRequest.Builder builder = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .GET();

        if (idToken != null && !idToken.isBlank()) {
            builder.header("Authorization", "Bearer " + idToken);
        }

        HttpResponse<String> res;
        try {
            res = CLIENT.send(builder.build(), HttpResponse.BodyHandlers.ofString());
        } catch (IOException | InterruptedException e) {
            throw new FirestoreException("Unable to retrieve elections.", e);
        }
        System.out.println("[ElectionDAO.getElections] HTTP " + res.statusCode());

        if (res.statusCode() >= 200 && res.statusCode() < 300) {
            JsonObject root = JsonParser.parseString(res.body()).getAsJsonObject();
            if (root.has("documents")) {
                JsonArray docs = root.getAsJsonArray("documents");
                for (JsonElement el : docs) {
                    JsonObject doc = el.getAsJsonObject();
                    ElectionData election = parseElection(doc);
                    // Match joinCode if provided, or if match ignore case
                    if (joinCode == null || joinCode.isBlank()
                            || joinCode.equalsIgnoreCase(election.getJoinCode())) {
                        result.add(election);
                    }
                }
            }
        } else {
            System.err.println("[ElectionDAO.getElections] Error response: " + res.body());
        }

        // Sort by createdAt descending
        result.sort((a, b) -> Long.compare(b.getCreatedAt(), a.getCreatedAt()));
        System.out.println("[ElectionDAO.getElections] Loaded " + result.size() + " elections for joinCode: " + joinCode);
        return result;
    }

    // =========================================================
    // PARSE FIRESTORE DOCUMENT → ElectionData
    // =========================================================

    private static ElectionData parseElection(JsonObject doc) {
        ElectionData e = new ElectionData();

        // Extract doc ID from "name" field: "projects/.../documents/Elections/{id}"
        if (doc.has("name")) {
            String name = doc.get("name").getAsString();
            e.setId(name.substring(name.lastIndexOf('/') + 1));
        }

        if (!doc.has("fields")) return e;
        JsonObject fields = doc.getAsJsonObject("fields");

        e.setTitle(getString(fields, "title"));
        e.setDescription(getString(fields, "description"));
        e.setStartDateTime(getString(fields, "startDateTime"));
        e.setEndDateTime(getString(fields, "endDateTime"));
        e.setStatus(getString(fields, "status"));
        e.setJoinCode(getString(fields, "joinCode"));

        // Parse positions array
        if (fields.has("positions")) {
            JsonObject posField = fields.getAsJsonObject("positions");
            if (posField.has("arrayValue")) {
                JsonObject arrVal = posField.getAsJsonObject("arrayValue");
                List<String> positions = new ArrayList<>();
                if (arrVal.has("values")) {
                    for (JsonElement v : arrVal.getAsJsonArray("values")) {
                        positions.add(v.getAsJsonObject().get("stringValue").getAsString());
                    }
                }
                e.setPositions(positions);
            }
        }

        if (fields.has("createdAt")) {
            JsonObject tsField = fields.getAsJsonObject("createdAt");
            if (tsField.has("integerValue")) {
                e.setCreatedAt(tsField.get("integerValue").getAsLong());
            }
        }

        return e;
    }

    // =========================================================
    // HELPERS
    // =========================================================

    private static JsonObject str(String value) {
        JsonObject o = new JsonObject();
        o.addProperty("stringValue", value != null ? value : "");
        return o;
    }

    private static JsonObject intVal(long value) {
        JsonObject o = new JsonObject();
        o.addProperty("integerValue", value);
        return o;
    }

    private static JsonObject toArrayValue(List<String> list) {
        JsonArray values = new JsonArray();
        if (list != null) {
            for (String s : list) {
                JsonObject sv = new JsonObject();
                sv.addProperty("stringValue", s);
                values.add(sv);
            }
        }
        JsonObject arrayValue = new JsonObject();
        arrayValue.add("values", values);
        JsonObject result = new JsonObject();
        result.add("arrayValue", arrayValue);
        return result;
    }

    public static String getString(JsonObject fields, String key) {
        if (fields == null || !fields.has(key)) return "";
        JsonObject field = fields.getAsJsonObject(key);
        if (field.has("stringValue")) return field.get("stringValue").getAsString();
        return "";
    }

    private static String encode(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8);
    }
}
